# Generated by Django 5.0.4 on 2024-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddUser",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=300)),
            ],
        ),
    ]
