# Generated by Django 5.0.4 on 2024-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_addblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="addblog",
            name="category",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
