# Generated by Django 5.0.4 on 2024-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_addblog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="addblog",
            name="file",
            field=models.FileField(default=None, upload_to="static/media"),
            preserve_default=False,
        ),
    ]
